### ISSUE TITLE
no such file or directory, open 'cert.pfx'

### ISSUE THREAD

**Issue by alexgoldstone** [tewarid/node-tcp-relay#5]
Just installed node-tcp-relay using:
```
sudo npm install -g node-tcp-relay
```

Then ran this:
```
tcprelays --relayPort 10080 --servicePort 10081
```

The output is:
```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'cert.pfx'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at new RelayServer (/root/.nvm/versions/node/v8.9.1/lib/node_modules/node-tcp-relay/relay-server.js:23:31)
    at Object.createRelayServer (/root/.nvm/versions/node/v8.9.1/lib/node_modules/node-tcp-relay/relay-server.js:10:16)
    at Object.<anonymous> (/root/.nvm/versions/node/v8.9.1/lib/node_modules/node-tcp-relay/relay-server-cli.js:23:34)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by tewarid** [comment]
Thanks for reporting the error.

**Comment by alexgoldstone** [comment]
I have installed `node-tcp-relay@0.0.12` and get the same issue:

```
fs.js:646
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'cert.pfx'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at new Listener (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/node-tcp-relay/relay-server.js:56:21)
    at new RelayServer (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/node-tcp-relay/relay-server.js:17:26)
    at Object.createRelayServer (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/node-tcp-relay/relay-server.js:9:16)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v8.9.1/lib/node_modules/node-tcp-relay/relay-server-cli.js:25:34)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```
